apiVersion: batch/v1
kind: Job
metadata:
  name: finalizer-purger
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccount: post-install-job
      containers:
        - name: post-install-job
          image: "bitnami/kubectl:latest"
          volumeMounts:
            - name: purger-script
              mountPath: /purge.sh
              subPath: purge.sh
              readOnly: true
          command:
            - "/purge.sh"
      volumes:
        - name: purger-script
          configMap:
            name: purger-script
            defaultMode: 0777
