apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ctrl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ctrl
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
