apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ctrl
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
