apiVersion: v1
kind: ServiceAccount
metadata:
  name: post-install-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
